// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'firebase_options.dart';
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAXUJ5-psMn6-PpXlkevgp0VUp90kkcqD8',
//     appId: '1:58332947068:web:7af28716de358ee7e3dff9',
//     messagingSenderId: '58332947068',
//     projectId: 'alp-depd',
//     authDomain: 'alp-depd.firebaseapp.com',
//     databaseURL: 'https://alp-depd-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'alp-depd.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCdmyk-StoWElTsqTHi-fOcHACL144dcg0',
//     appId: '1:58332947068:android:cc28dc465c2520d2e3dff9',
//     messagingSenderId: '58332947068',
//     projectId: 'alp-depd',
//     databaseURL: 'https://alp-depd-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'alp-depd.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD0btWuR30CXERLjGdegQb4DNl467YIA20',
//     appId: '1:58332947068:ios:c90c99ad73c0de32e3dff9',
//     messagingSenderId: '58332947068',
//     projectId: 'alp-depd',
//     databaseURL: 'https://alp-depd-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'alp-depd.firebasestorage.app',
//     iosBundleId: 'com.example.alpDepdFlutter',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyD0btWuR30CXERLjGdegQb4DNl467YIA20',
//     appId: '1:58332947068:ios:c90c99ad73c0de32e3dff9',
//     messagingSenderId: '58332947068',
//     projectId: 'alp-depd',
//     databaseURL: 'https://alp-depd-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'alp-depd.firebasestorage.app',
//     iosBundleId: 'com.example.alpDepdFlutter',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAXUJ5-psMn6-PpXlkevgp0VUp90kkcqD8',
//     appId: '1:58332947068:web:94f78224eb696059e3dff9',
//     messagingSenderId: '58332947068',
//     projectId: 'alp-depd',
//     authDomain: 'alp-depd.firebaseapp.com',
//     databaseURL: 'https://alp-depd-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'alp-depd.firebasestorage.app',
//   );
// }

